# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-symlinks
        exclude: ^scripts/airsim/
      - id: destroyed-symlinks
        exclude: ^scripts/airsim/
      - id: trailing-whitespace
        exclude: ^scripts/airsim/
      - id: end-of-file-fixer
        exclude: ^scripts/airsim/
      - id: check-yaml
        exclude: ^scripts/airsim/
      - id: check-toml
        exclude: ^scripts/airsim/
      - id: check-ast
        exclude: ^scripts/airsim/
      - id: check-added-large-files
        exclude: ^scripts/airsim/
        args: ["--maxkb=2000"]
      - id: check-merge-conflict
        exclude: ^scripts/airsim/
      - id: check-executables-have-shebangs
        exclude: ^scripts/airsim/
      - id: check-shebang-scripts-are-executable
        exclude: ^scripts/airsim/
      - id: detect-private-key
        exclude: ^scripts/airsim/
      - id: debug-statements
        exclude: ^scripts/airsim/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.991"
    hooks:
      - id: mypy
        additional_dependencies:
          - "numpy >=1.19.4"
          - "types-requests>-2.28"
          - "types-PyYAML"
        args:
          [
            --no-strict-optional,
            --ignore-missing-imports,
            --exclude=scripts/airsim/,
          ]
  - repo: https://github.com/python/black
    rev: 23.1.0
    hooks:
      - id: black
        exclude: ^scripts/airsim/

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        exclude: ^scripts/airsim/
        types: [python]
        args: [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--rcfile=.pylintrc", # Link to your config file
          ]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.0.254"
    hooks:
      - id: ruff
        exclude: ^scripts/airsim/
